apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://host.docker.internal:9090 # change to internal docker named service
    basicAuth: false
    isDefault: true
    editable: true