{
 "title": "Database load",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overall DB Execution Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overall DB Load (last 5 minutes - cluster wide)",
   "type": "timeseries",
   "description": "Measures how much load a plugin is putting on the database\n\nThis underpins all DB operations in Jira, which means the db.ao and the db.sal metrics here are a subset.\n\nIf a plugin triggers SQL queries that are abnormal in quantity or duration, contact the app vendor to investigate. The invokerPluginKey tag shows which plugin is doing something that results in database queries being executed.\n\nThere is an optional tag that can be enabled sql which can be used for debugging exactly what the database queries are. It’s not recommended to enable this optional tag in production, it will lead to rapidly growing memory consumption.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "# We do this because the average of averages is not the real average. We must weigh them by the count\nsum without (instance) ((com_atlassian_jira_metrics_Mean{name=\"executionTime\", category00=\"db\", category01=\"core\"}) * \n(delta(com_atlassian_jira_metrics_Count{name=\"executionTime\", category00=\"db\", category01=\"core\"}[5m])))\n",
     "legendFormat": "{{tag_invokerPluginKey}}"
    }
   ]
  },
  {
   "title": "DB Execution Times (Cluster Wide)",
   "type": "table",
   "description": "Measures how long it takes for a DB Query to be executed from being provided a SQL statement to providing the results. \n\nThis underpins all DB operations in Jira, which means the db.ao and the db.sal metrics here are a subset.\n\nIf a plugin triggers SQL queries that are abnormal in quantity or duration, contact the app vendor to investigate. The invokerPluginKey tag shows which plugin is doing something that results in database queries being executed.\n\nThere is an optional tag that can be enabled sql which can be used for debugging exactly what the database queries are. It’s not recommended to enable this optional tag in production, it will lead to rapidly growing memory consumption.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg without (instance, tag_query, category00, category01) (com_atlassian_jira_metrics_Mean{name=\"executionTime\", category00=\"db\", category01=\"core\"})"
    },
    {
     "expr": "sum without (instance, tag_query, category00, category01) (com_atlassian_jira_metrics_Count{name=\"executionTime\", category00=\"db\", category01=\"core\"})"
    },
    {
     "expr": "max without (instance, tag_query, category00, category01) (com_atlassian_jira_metrics_99thPercentile{name=\"executionTime\", category00=\"db\", category01=\"core\"})"
    }
   ]
  },
  {
   "title": "DB Execution Time (p99 - per node)",
   "type": "timeseries",
   "description": "Measures how long it takes for a DB Query to be executed from being provided a SQL statement to providing the results. \n\nThis underpins all DB operations in Jira, which means the db.ao and the db.sal metrics here are a subset.\n\nIf a plugin triggers SQL queries that are abnormal in quantity or duration, contact the app vendor to investigate. The invokerPluginKey tag shows which plugin is doing something that results in database queries being executed.\n\nThere is an optional tag that can be enabled sql which can be used for debugging exactly what the database queries are. It’s not recommended to enable this optional tag in production, it will lead to rapidly growing memory consumption.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_atlassian_jira_metrics_99thPercentile{name=\"executionTime\", category00=\"db\", category01=\"core\"}",
     "legendFormat": "{{tag_invokerPluginKey}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Cumulative count of DB executions (cluster wide) ",
   "type": "timeseries",
   "description": "Measures how long it takes for a DB Query to be executed from being provided a SQL statement to providing the results. \n\nThis underpins all DB operations in Jira, which means the db.ao and the db.sal metrics here are a subset.\n\nIf a plugin triggers SQL queries that are abnormal in quantity or duration, contact the app vendor to investigate. The invokerPluginKey tag shows which plugin is doing something that results in database queries being executed.\n\nThere is an optional tag that can be enabled sql which can be used for debugging exactly what the database queries are. It’s not recommended to enable this optional tag in production, it will lead to rapidly growing memory consumption.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without (instance, tag_entityType) (com_atlassian_jira_metrics_Count{category00=\"db\", category01=\"core\", name=\"executionTime\"})",
     "legendFormat": "{{tag_invokerPluginKey}}"
    }
   ]
  },
  {
   "title": "DB Execution Times (mean last 5 minutes - cluster wide)",
   "type": "timeseries",
   "description": "Measures how long it takes for a DB Query to be executed from being provided a SQL statement to providing the results. \n\nThis underpins all DB operations in Jira, which means the db.ao and the db.sal metrics here are a subset.\n\nIf a plugin triggers SQL queries that are abnormal in quantity or duration, contact the app vendor to investigate. The invokerPluginKey tag shows which plugin is doing something that results in database queries being executed.\n\nThere is an optional tag that can be enabled sql which can be used for debugging exactly what the database queries are. It’s not recommended to enable this optional tag in production, it will lead to rapidly growing memory consumption.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "# We do this because the average of averages is not the real average. We must weigh them by the count\n(sum without (instance) ((com_atlassian_jira_metrics_Mean{name=\"executionTime\", category00=\"db\", category01=\"core\"}) * \n(delta(com_atlassian_jira_metrics_Count{name=\"executionTime\", category00=\"db\", category01=\"core\"}[5m]))) /\n(sum without (instance) (delta(com_atlassian_jira_metrics_Count{name=\"executionTime\", category00=\"db\", category01=\"core\"}[5m]))))\n",
     "legendFormat": "{{tag_invokerPluginKey}}"
    }
   ]
  },
  { "title": "AO's EntityManager by method", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Load via AO's EntityManager (mean last 5 minutes - cluster wide)",
   "type": "timeseries",
   "description": "Measures how long an AO operation (create, find, delete, deleteWithSQL, get, stream, count) that uses the Entity Manager takes.\n\nThe operation query might be long running, or the database is under load. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "# We do this because the average of averages is not the real average. We must weigh them by the count\n(sum without (instance, tag_entityType) ((com_atlassian_jira_metrics_Mean{category00=\"db\", category01=\"ao\", category02=\"entityManager\"}) * \n(delta(com_atlassian_jira_metrics_Count{category00=\"db\", category01=\"ao\", category02=\"entityManager\"}[5m]))))\n",
     "legendFormat": "{{tag_invokerPluginKey}} - {{name}}"
    }
   ]
  },
  {
   "title": "Operation times via AO's EntityManager (mean last 5 minutes - cluster wide)",
   "type": "timeseries",
   "description": "Measures how long an AO operation (create, find, delete, deleteWithSQL, get, stream, count) that uses the Entity Manager takes.\n\nThe operation query might be long running, or the database is under load. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "# We do this because the average of averages is not the real average. We must weigh them by the count\n(sum without (instance, tag_entityType) ((com_atlassian_jira_metrics_Mean{category00=\"db\", category01=\"ao\", category02=\"entityManager\"}) * \n(delta(com_atlassian_jira_metrics_Count{category00=\"db\", category01=\"ao\", category02=\"entityManager\"}[5m])))) /\n(sum without (instance, tag_entityType) (delta(com_atlassian_jira_metrics_Count{category00=\"db\", category01=\"ao\", category02=\"entityManager\"}[5m])))\n",
     "legendFormat": "{{tag_invokerPluginKey}} - {{name}}"
    }
   ]
  },
  {
   "title": "Cumulative count using AO's EntityManager (cluster wide)",
   "type": "timeseries",
   "description": "Measures the total count of AO operations (create, find, delete, deleteWithSQL, get, stream, count) by the plugins.\n\nThe operation query might be long running, or the database is under load. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without (instance, tag_entityType) (com_atlassian_jira_metrics_Count{category00=\"db\", category01=\"ao\", category02=\"entityManager\"})",
     "legendFormat": "{{tag_invokerPluginKey}} - {{name}} "
    }
   ]
  },
  {
   "title": "Operation times via AO's EntityManager (p99)",
   "type": "timeseries",
   "description": "Measures how long an AO operation (create, find, delete, deleteWithSQL, get, stream, count) that uses the Entity Manager takes.\n\nThe operation query might be long running, or the database is under load. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_atlassian_jira_metrics_99thPercentile{category00=\"db\", category01=\"ao\", category02=\"entityManager\"}",
     "legendFormat": "{{tag_invokerPluginKey}} - {{name}} - {{tag_entityType}}"
    }
   ]
  },
  { "title": "AO's executeInTransaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Load via AO's executeInTransaction (mean last 5 minutes - cluster wide)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "# We do this because the average of averages is not the real average. We must weigh them by the count\n(sum without (instance, tag_taskName) ((com_atlassian_jira_metrics_Mean{category00=\"db\", category01=\"ao\", name=\"executeInTransaction\"}) * \n(delta(com_atlassian_jira_metrics_Count{category00=\"db\", category01=\"ao\", name=\"executeInTransaction\"}[5m]))))\n",
     "legendFormat": "{{tag_invokerPluginKey}}"
    }
   ]
  },
  {
   "title": "Operation times via AO's executeInTransaction (mean last 5 minutes - cluster wide)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "# We do this because the average of averages is not the real average. We must weigh them by the count\n(sum without (instance, tag_taskName) ((com_atlassian_jira_metrics_Mean{category00=\"db\", category01=\"ao\", name=\"executeInTransaction\"}) * \n(delta(com_atlassian_jira_metrics_Count{category00=\"db\", category01=\"ao\", name=\"executeInTransaction\"}[5m])))) /\n(sum without (instance, tag_taskName) (delta(com_atlassian_jira_metrics_Count{category00=\"db\", category01=\"ao\", name=\"executeInTransaction\"}[5m])))\n",
     "legendFormat": "{{tag_invokerPluginKey}}"
    }
   ]
  },
  {
   "title": "Cumulative count using AO's executeInTransaction (cluster wide)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without (instance, tag_taskName) (com_atlassian_jira_metrics_Count{category00=\"db\", category01=\"ao\", name=\"executeInTransaction\"})",
     "legendFormat": "{{tag_invokerPluginKey}}"
    }
   ]
  },
  {
   "title": "Operation times via AO's executeInTransaction (p99)",
   "type": "timeseries",
   "description": "Measures how long an AO operation (create, find, delete, deleteWithSQL, get, stream, count) that uses the Entity Manager takes.\n\nThe operation query might be long running, or the database is under load. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_atlassian_jira_metrics_99thPercentile{category00=\"db\", category01=\"ao\", name=\"executeInTransaction\"}",
     "legendFormat": "{{tag_invokerPluginKey}} - {{tag_taskName}}"
    }
   ]
  },
  {
   "title": "Total active operations running  via AO's executeInTransaction (current - cluster wide)",
   "type": "gauge",
   "description": "Measures how long an AO transaction takes, when executed inside the TransactionCallBack. This is mainly used by Confluence plugins.\n\nThe transaction can have many AO operations, it can be either there are too many operations or the query is long running, or the database is under load. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, tag_taskName, tag_invokerPluginKey) (com_atlassian_jira_metrics_Value{category00=\"db\",category01=\"ao\",name=\"executeInTransaction\", tag_statistic=\"active\"})"
    }
   ]
  },
  {
   "title": "Active operations running via AO's executeInTransaction (over time - active count)",
   "type": "timeseries",
   "description": "Measures how long an AO transaction takes, when executed inside the TransactionCallBack. This is mainly used by Confluence plugins.\n\nThe transaction can have many AO operations, it can be either there are too many operations or the query is long running, or the database is under load. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "targets": [
    {
     "expr": "sum without (instance) (com_atlassian_jira_metrics_Value{category00=\"db\",category01=\"ao\",name=\"executeInTransaction\", tag_statistic=\"active\"})",
     "legendFormat": "{{ tag_invokerPluginKey }} - {{tag_taskName}} (task)"
    }
   ]
  },
  { "title": "SAL's transactionalExecutor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Load via SAL's transactionalExecutor (mean last 5 minutes - cluster wide)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "# We do this because the average of averages is not the real average. We must weigh them by the count\n(sum without (instance, tag_taskName) ((com_atlassian_jira_metrics_Mean{category00=\"db\", category01=\"sal\", name=\"transactionalExecutor\"}) * \n(delta(com_atlassian_jira_metrics_Count{category00=\"db\", category01=\"sal\", name=\"transactionalExecutor\"}[5m]))))\n",
     "legendFormat": "{{tag_invokerPluginKey}}"
    }
   ]
  },
  {
   "title": "Operation times via SAL's transactionalExecutor (mean last 5 minutes - cluster wide)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "# We do this because the average of averages is not the real average. We must weigh them by the count\n(sum without (instance, tag_taskName) ((com_atlassian_jira_metrics_Mean{category00=\"db\", category01=\"ao\", name=\"executeInTransaction\"}) * \n(delta(com_atlassian_jira_metrics_Count{category00=\"db\", category01=\"ao\", name=\"executeInTransaction\"}[5m])))) /\n(sum without (instance, tag_taskName) (delta(com_atlassian_jira_metrics_Count{category00=\"db\", category01=\"ao\", name=\"executeInTransaction\"}[5m])))\n",
     "legendFormat": "{{tag_invokerPluginKey}}"
    }
   ]
  },
  {
   "title": "Cumulative count using SAL's transactionalExecutor (cluster wide)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without (instance, tag_taskName) (com_atlassian_jira_metrics_Count{category00=\"db\", category01=\"sal\", name=\"transactionalExecutor\"})",
     "legendFormat": "{{tag_invokerPluginKey}}"
    }
   ]
  },
  {
   "title": "Operation times via SAL's transactionalExecutor (p99)",
   "type": "timeseries",
   "description": "Measures how long an AO operation (create, find, delete, deleteWithSQL, get, stream, count) that uses the Entity Manager takes.\n\nThe operation query might be long running, or the database is under load. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_atlassian_jira_metrics_99thPercentile{category00=\"db\", category01=\"sal\", name=\"transactionalExecutor\"}",
     "legendFormat": "{{ tag_invokerPluginKey }} - {{tag_taskName}} (task)"
    }
   ]
  },
  {
   "title": "Total active operations running  via SAL's transactionalExecutor (current - cluster wide)",
   "type": "gauge",
   "description": "Measures how long an SAL transaction takes, when executed inside the DefaultTransactionalExecutor.\n\nThe transaction can have many SAL operations, it can be either there are too many operations or the query is long running, or the database is under load. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, tag_taskName, tag_invokerPluginKey) (com_atlassian_jira_metrics_Value{category00=\"db\",category01=\"sal\",name=\"transactionalExecutor\", tag_statistic=\"active\"})"
    }
   ]
  },
  {
   "title": "Active operations using SAL's transactionalExecutor (over time - active count)",
   "type": "timeseries",
   "description": "Measures how long an SAL transaction takes, when executed inside the DefaultTransactionalExecutor.\n\nThe transaction can have many SAL operations, it can be either there are too many operations or the query is long running, or the database is under load. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without (instance) (com_atlassian_jira_metrics_Value{category00=\"db\",category01=\"sal\",name=\"transactionalExecutor\",tag_statistic=\"active\"})",
     "legendFormat": "{{ tag_invokerPluginKey }} - {{tag_taskName}} (task)"
    }
   ]
  },
  { "title": "AO upgrade tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "AO Upgrade Tasks - (current - active count)",
   "type": "gauge",
   "description": "Measures how long an App is taking to upgrade a part of the data that it stores in the database.\n\nUpgrade tasks happen when an App is both updated and enabled, during this time the App’s functionality will probably be unavailable, and it may temporarily increase load on the database and the node the upgrade task is running on.\n\nIf an App stores a lot of data in database then this may take a while to run, if possible, try to schedule upgrading Apps with large amounts of data in off-peak hours.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, tag_fromPluginKey, tag_taskName) (com_atlassian_jira_metrics_Value{category00=\"db\",category01=\"ao\",name=\"upgradeTask\",tag_statistic=\"active\",tag_subCategory=\"current\"})"
    }
   ]
  },
  {
   "title": "AO Upgrade Tasks - (over time - active count)",
   "type": "timeseries",
   "description": "Measures how long an App is taking to upgrade a part of the data that it stores in the database.\n\nUpgrade tasks happen when an App is both updated and enabled, during this time the App’s functionality will probably be unavailable, and it may temporarily increase load on the database and the node the upgrade task is running on.\n\nIf an App stores a lot of data in database then this may take a while to run, if possible, try to schedule upgrading Apps with large amounts of data in off-peak hours.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "targets": [
    {
     "expr": "sum without (instance) (com_atlassian_jira_metrics_Value{category00=\"db\",category01=\"ao\",name=\"upgradeTask\",tag_statistic=\"active\",tag_subCategory=\"current\"})",
     "legendFormat": "{{ tag_invokerPluginKey }} - {{tag_taskName}} (task)"
    }
   ]
  }
 ]
}