version: "3.7"
services:
    prometheus:
      image: prom/prometheus
      ports:
        - 9090:9090
      volumes:
        - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    grafana:
      image: grafana/grafana-oss
      ports:
        - 3000:3000
      volumes:
        - ../grafana/provisioning:/etc/grafana/provisioning
     
