{
 "title": "Jira - IPD - Database",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Database Connection State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "com_atlassian_jira_metrics_Value{category00=\"db\", category01=\"connection\", category02=\"state\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Connection Pool Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "com_atlassian_jira_metrics_Value{category00=\"db\", category01=\"connection\", category02=\"pool\", category03=\"numActive\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_atlassian_jira_metrics_Value{category00=\"db\", category01=\"connection\", category02=\"pool\", category03=\"numIdle\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "com_atlassian_jira_metrics_Value\n {category00=\"db\",category01=\"connection\",category02=\"latency\"\n }",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_atlassian_jira_metrics_95thPercentile{category00=\"db\", category01=\"connection\", category02=\"latency\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}