# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: 
  push:
    tags:
    - 'release-*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'atlassian-monitoring-stack-for-jira.zip'
        exclusions: '*.git* *.atlassian* *.md *.json docs/Development.md'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "atlassian-monitoring-stack-for-jira.zip"
        token: ${{ secrets.GITHUB_TOKEN }}